# NumPy Exercises - 100 NumPy exercises

This notebook contains practice exercises for learning NumPy fundamentals.

## 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

## 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy version:", np.__version__)

np.show_config()
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    s

## 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)

## 4. How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
size_bytes = Z.size * Z.itemsize
nbytes = Z.nbytes

## 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# help(np.add)  # Not run to avoid blocking output

## 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1

## 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Z = np.arange(10, 50)

## 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)[::-1]

## 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Z = np.arange(9).reshape(3, 3)

## 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])

## 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
Z = np.eye(3)

## 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
Z = np.random.random((3,3,3))

## 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()

## 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
Z = np.random.random(30)
mean = Z.mean()

## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0

## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

## 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = 0.3 == 3 * 0.1

## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Z = np.diag(np.arange(1, 5), k=-1)

## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1

## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
idx = np.unravel_index(100, (6,7,8))

## 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
Z = np.tile([[0,1],[1,0]], (4,4))

## 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
Z = np.random.random((5,5))
Z = (Z - np.min(Z)) / (np.max(Z) - np.min(Z))

## 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])

## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 26. What is the output of the following script? (★☆☆)

```bash
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


## 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z*Z
2 << Z >> 2
Z <- Z
1jZ
Z/1/1
Z<Z>Z

In [27]:
Z = np.arange(3)
legal1 = Z*Z
legal2 = 2 << Z >> 2
legal3 = 1j*Z
legal4 = Z/1/1

## 28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [28]:
res1 = np.array(0) / np.array(0)
res2 = np.array(0) // np.array(0)
res3 = np.array([np.nan]).astype(int).astype(float)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2460\2260463556.py:1: RuntimeWarning: invalid value encountered in divide
  res1 = np.array(0) / np.array(0)
C:\Users\Dell\AppData\Local\Temp\ipykernel_2460\2260463556.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  res2 = np.array(0) // np.array(0)
C:\Users\Dell\AppData\Local\Temp\ipykernel_2460\2260463556.py:3: RuntimeWarning: invalid value encountered in cast
  res3 = np.array([np.nan]).astype(int).astype(float)


## 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Z = np.random.uniform(-10, +10, 10)
rounded = np.copysign(np.ceil(np.abs(Z)), Z)

## 30. How to find common values between two arrays? (★☆☆)
```bash
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
print(np.intersect1d(A, B))
```

In [30]:
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
common = np.intersect1d(A, B)

## 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [31]:
import warnings
warnings.filterwarnings('ignore')

## 32. Is the following expressions true? (★☆☆)


In [32]:
comparison = (np.sqrt(-1) == np.emath.sqrt(-1))

## 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

## 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
```bash
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)
```

In [34]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

## 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)



In [35]:
A = np.ones(3)
B = np.ones(3) * 2
A += B
A *= -A/2
print(A)

[-4.5 -4.5 -4.5]


## 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
```bash


In [36]:
Z = np.random.uniform(0, 10, 10)
print(Z.astype(int))
print(np.floor(Z))
print(np.ceil(Z)-1)
print(np.trunc(Z))

[9 9 9 7 5 7 8 2 6 7]
[9. 9. 9. 7. 5. 7. 8. 2. 6. 7.]
[9. 9. 9. 7. 5. 7. 8. 2. 6. 7.]
[9. 9. 9. 7. 5. 7. 8. 2. 6. 7.]


## 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [37]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [38]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=int, count=10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


## 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
```bash


In [39]:
Z = np.linspace(0, 1, 12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]



## 40. Create a random vector of size 10 and sort it (★★☆)


In [40]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.19605524 0.33631068 0.36752439 0.42758185 0.56328745 0.75295642
 0.83785748 0.86246554 0.99231372 0.99442494]



## 41. How to sum a small array faster than np.sum? (★★☆)


In [41]:
Z = np.arange(10)
print(np.add.reduce(Z))

45


## 42. Consider two random array A and B, check if they are equal (★★☆)


In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A, B)
print(equal)

False


## 43. Make an array immutable (read-only) (★★☆)


In [43]:

Z = np.zeros(10)
Z[0] = 1
Z.flags.writeable = False


## 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [44]:

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)


## 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [45]:

Z = np.random.random(10)
Z[Z.argmax()] = 0


## 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [46]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))


## 47. Given two arrays, X and Y, construct the Cauchy matrix C (C_{i,j} =1/(x_i - y_j)) (★★☆)



In [47]:

X = np.arange(8)
Y = X + 0.5
C = 1.0 / (X[:,None] - Y[None,:])

## 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [48]:

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


## 49. How to print all the values of an array? (★★☆)


In [49]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [50]:

Z = np.arange(100)
v = 42
print(Z[(np.abs(Z-v)).argmin()])


42


## 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


In [51]:

Z = np.zeros(10, [('position', [('x', float), ('y', float)]),
                  ('color',    [('r', float), ('g', float), ('b', float)])])


## 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [52]:

Z = np.random.random((100,2))
X, Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
distances = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)


## 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [53]:

Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)


## 54. How to read the following file? (★★☆)
```bash
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11


In [54]:

from io import StringIO
s = StringIO("1, 2, 3, 4, 5\n6,  ,  , 7, 8\n ,  , 9,10,11")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)


## 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [55]:

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## 56. Generate a generic 2D Gaussian-like array (★★☆)


In [56]:

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ))


## 57. How to randomly place p elements in a 2D array? (★★☆)


In [57]:

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)


## 58. Subtract the mean of each row of a matrix (★★☆)


In [58]:

X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)


## 59. How to sort an array by the nth column? (★★☆)


In [59]:

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[7 2 4]
 [9 2 5]
 [1 5 1]]
[[7 2 4]
 [9 2 5]
 [1 5 1]]


## 60. How to tell if a given 2D array has null columns? (★★☆)


In [60]:

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


True


## 61. Find the nearest value from a given value in an array (★★☆)


In [61]:

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]


## 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [62]:

A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
for x, y in np.nditer([A, B]):
    print(x, y, x + y)


0 0 0
1 0 1
2 0 2
0 1 1
1 1 2
2 1 3
0 2 2
1 2 3
2 2 4


## 63. Create an array class that has a name attribute (★★☆)


In [63]:

class NamedArray(np.ndarray):
    def __new__(cls, *args, name="no name", **kwargs):
        obj = super(NamedArray, cls).__new__(cls, *args, **kwargs)
        obj.name = name
        return obj
Z = NamedArray(shape=(3,3), name="example")


## 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [64]:

Z = np.zeros(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength=len(Z))


## 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [65]:

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)


## 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [66]:

w, h = 16, 16
I = np.random.randint(0, 2, (w, h, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n_unique = len(colors)


## 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [67]:

A = np.random.random((3,4,3,4))
result = A.sum(axis=(-2,-1))


## 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


In [68]:

D = np.random.uniform(0, 10, 100)
S = np.random.randint(0, 10, 100)
means = [D[S == i].mean() for i in np.unique(S)]


## 69. How to get the diagonal of a dot product? (★★★)


In [69]:

A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))
diag = np.einsum('ij,ji->i', A, B)


## 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [70]:

Z = np.array([1,2,3,4,5])
Z0 = np.zeros(4 * len(Z) - 3)
Z0[::4] = Z


## 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [71]:
A = np.ones((5,5,3))
B = np.ones((5,5))
C = A * B[...,None]


## 72. How to swap two rows of an array? (★★★)


In [72]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]


## 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


In [73]:
faces = np.random.randint(0, 20, (10, 3))
F = np.roll(faces, -1, axis=1)
segments = np.sort(np.concatenate([faces, F]), axis=1)
unique_segments = np.unique(segments, axis=0)


## 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [74]:
C = np.bincount(np.random.randint(0, 4, 10))
A = np.repeat(np.arange(len(C)), C)


## 75. How to compute averages using a sliding window over an array? (★★★)


In [75]:
Z = np.arange(20)
window = 4
averages = np.convolve(Z, np.ones(window)/window, mode='valid')


## 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [76]:
Z = np.arange(1, 8)
rows = 3
result = np.lib.stride_tricks.sliding_window_view(Z, rows)


## 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [77]:
Z_bool = np.array([True, False, True])
np.logical_not(Z_bool, out=Z_bool)
Z_float = np.random.uniform(-1.0, 1.0, 10)
np.negative(Z_float, out=Z_float)


array([ 0.70068361,  0.29166105, -0.47392845,  0.75511829,  0.99190468,
       -0.82639816, -0.83591535,  0.77606252,  0.38014297,  0.06404448])

## 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [78]:
P0 = np.random.uniform(0,1,(10,2))
P1 = np.random.uniform(0,1,(10,2))
p = np.random.uniform(0,1,(2))
d = np.abs(np.cross(P1-P0, P0-p))/np.linalg.norm(P1-P0, axis=1)


## 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [79]:
P0 = np.random.uniform(0,1,(10,2))
P1 = np.random.uniform(0,1,(10,2))
P = np.random.uniform(0,1,(10,2))
d = np.abs(np.cross(P1-P0, P0-P[:,None]))/np.linalg.norm(P1-P0, axis=1)


## 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)


In [80]:
def extract_subpart(A, center, shape, fill=0):
    output = np.full(shape, fill, dtype=A.dtype)
    slices = []
    for i in range(len(shape)):
        start = max(center[i] - shape[i]//2, 0)
        end = min(center[i] + shape[i]//2 + shape[i]%2, A.shape[i])
        out_start = max(0, shape[i]//2 - center[i])
        out_end = out_start + (end - start)
        slices.append(slice(start, end))
        output[(slice(None),)*i + (slice(out_start, out_end),)] = A[slices[i]]
    return output

## 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [81]:
Z = np.arange(1,15)
R = np.lib.stride_tricks.sliding_window_view(Z, 4)
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## 82. Compute a matrix rank (★★★)


In [82]:
Z = np.random.uniform(0, 1, (10, 10))
rank = np.linalg.matrix_rank(Z)
print(rank)


10


## 83. How to find the most frequent value in an array? (★★★)


In [83]:
Z = np.random.randint(0, 10, 50)
most_frequent = np.bincount(Z).argmax()
print(most_frequent)

0


## 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [84]:
Z = np.random.random((10,10))
blocks = np.lib.stride_tricks.sliding_window_view(Z, (3,3))
print(blocks)



[[[[0.94014611 0.83106355 0.33624203]
   [0.74258725 0.67973326 0.69056588]
   [0.83867553 0.75978614 0.35171207]]

  [[0.83106355 0.33624203 0.03473892]
   [0.67973326 0.69056588 0.7143443 ]
   [0.75978614 0.35171207 0.17538489]]

  [[0.33624203 0.03473892 0.14611354]
   [0.69056588 0.7143443  0.47261675]
   [0.35171207 0.17538489 0.54190281]]

  [[0.03473892 0.14611354 0.82025758]
   [0.7143443  0.47261675 0.82453259]
   [0.17538489 0.54190281 0.92723077]]

  [[0.14611354 0.82025758 0.87907031]
   [0.47261675 0.82453259 0.03082687]
   [0.54190281 0.92723077 0.78378672]]

  [[0.82025758 0.87907031 0.45414076]
   [0.82453259 0.03082687 0.54553146]
   [0.92723077 0.78378672 0.77935098]]

  [[0.87907031 0.45414076 0.67193145]
   [0.03082687 0.54553146 0.76170787]
   [0.78378672 0.77935098 0.02341267]]

  [[0.45414076 0.67193145 0.98067876]
   [0.54553146 0.76170787 0.71970831]
   [0.77935098 0.02341267 0.72602232]]]


 [[[0.74258725 0.67973326 0.69056588]
   [0.83867553 0.75978614 0.3517

In [85]:
## 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [86]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)
Z = np.zeros((5,5)).view(Symetric)
Z[2,3] = 1
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 86. Consider a set of p matrices of shape (n,n) and a set of p vectors of shape (n,1). How to compute the sum of the p matrix products at once? (★★★)


In [87]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
sums = np.einsum('ijk,ikl->i', M, V)
print(sums)

[400. 400. 400. 400. 400. 400. 400. 400. 400. 400.]



## 87. Let A be a 1D array and B a 2D array, how to compute the sum of A and each row of B? (★★★)


In [88]:
A = np.arange(3)
B = np.arange(6).reshape(2,3)
sum_rows = A + B
print(sum_rows)


[[0 2 4]
 [3 5 7]]


## 88. Consider a generator function that generates 10 integers and use it to build an array (★★★)


In [89]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=int, count=10)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


## 89. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [90]:
Z_bool = np.array([True, False, True])
np.logical_not(Z_bool, out=Z_bool)
print(Z_bool)
Z_float = np.random.uniform(-1.0, 1.0, 10)
np.negative(Z_float, out=Z_float)
print(Z_float)


[False  True False]
[ 0.69627204  0.61889556  0.70167048  0.27038156 -0.29540859 -0.44576889
  0.04800061  0.41670237 -0.65578673 -0.19710998]


## 90. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [91]:
Z = np.arange(1, 8)
rows = 3
result = np.lib.stride_tricks.sliding_window_view(Z, rows)
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


## 91. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order? (★★★)


In [96]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
result = []
for b in B:
    mask = np.array([all(x in row for x in b) for row in A], dtype=bool)
    result.append(A[mask])
print("A:\n", A)
print("B:\n", B)
print("Rows of A containing all elements of each row of B (regardless of order):")
for i, rows in enumerate(result):
    print(f"B[{i}]:\n{rows}")

A:
 [[2 3 3]
 [1 1 2]
 [2 1 0]
 [2 0 3]
 [1 2 3]
 [2 3 1]
 [1 3 1]
 [1 3 2]]
B:
 [[1 0]
 [1 2]]
Rows of A containing all elements of each row of B (regardless of order):
B[0]:
[[2 3 3]
 [1 1 2]
 [2 1 0]
 [2 0 3]
 [1 2 3]
 [2 3 1]
 [1 3 1]
 [1 3 2]]
B[1]:
[[2 3 3]
 [1 1 2]
 [2 1 0]
 [2 0 3]
 [1 2 3]
 [2 3 1]
 [1 3 1]
 [1 3 2]]


## 92. Considering a 10x3 matrix, extract rows with unequal values (e.g., [2,2,3]) (★★★)


In [97]:
Z = np.random.randint(0,5,(10,3))
rows = Z[~(Z[:,0] == Z[:,1]) | ~(Z[:,1] == Z[:,2])]
print(rows)



[[1 2 1]
 [4 0 3]
 [2 4 2]
 [1 3 3]
 [4 3 1]
 [2 1 3]
 [0 0 2]
 [1 4 2]
 [3 1 4]
 [4 1 0]]


In [98]:
## 93. Convert a vector of ints into a matrix binary representation (★★★)


In [99]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I[:,None] & (1 << np.arange(8))) > 0).astype(int)
print(B)


[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


## 94. Given a two dimensional array, how to extract unique rows? (★★★)


In [100]:

Z = np.random.randint(0,2,(6,3))
unique_rows = np.unique(Z, axis=0)
print(unique_rows)



[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]]


## 95. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul (★★★)


In [101]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
inner = np.einsum('i,i->', A, B)
outer = np.einsum('i,j->ij', A, B)
sum_ = np.einsum('i->', A)
mul = np.einsum('i->', A*B)
print(inner, outer, sum_, mul)


3.375918400586144 [[0.30099093 0.02353855 0.5576635  0.42532688 0.27403817 0.1591115
  0.54164037 0.50528127 0.17140894 0.36550477]
 [0.50105768 0.03918448 0.92833887 0.70803894 0.45618959 0.2648719
  0.90166527 0.84113851 0.28534337 0.60845345]
 [0.07937505 0.00620741 0.1470628  0.11216399 0.07226727 0.04195968
  0.1428373  0.13324896 0.04520267 0.09638815]
 [0.31951184 0.02498695 0.59197827 0.45149856 0.29090059 0.16890213
  0.57496919 0.5363728  0.18195627 0.38799541]
 [0.38021233 0.02973395 0.70444162 0.53727374 0.34616555 0.20098996
  0.68420117 0.63827229 0.21652411 0.46170633]
 [0.43380429 0.03392503 0.80373459 0.61300394 0.39495853 0.22932005
  0.78064119 0.72823851 0.24704377 0.5267851 ]
 [0.36473421 0.0285235  0.67576441 0.51540179 0.33207345 0.19280783
  0.65634794 0.61228878 0.2077096  0.44291067]
 [0.37892753 0.02963347 0.70206119 0.5354582  0.3449958  0.20031078
  0.68188914 0.63611546 0.21579244 0.46014615]
 [0.49153823 0.03844002 0.91070164 0.69458712 0.44752259 0.25983

## 96. Considering a path described by two vectors (X,Y), how to interpolate it with equidistant samples? (★★★)


In [102]:
phi = np.arange(0, 2*np.pi, 0.1)
a, b = 1, 1
x = a*np.cos(phi)
y = b*np.sin(phi)
d = np.cumsum(np.sqrt(np.diff(x)**2 + np.diff(y)**2))
d = np.insert(d, 0, 0)
equidistant = np.linspace(0, d.max(), 20)
x_interp = np.interp(equidistant, d, x)
y_interp = np.interp(equidistant, d, y)
print(x_interp, y_interp)


[ 1.          0.94631662  0.79349697  0.55741971  0.26236558 -0.06066636
 -0.37704904 -0.65399577 -0.86185543 -0.97797081 -0.99146425 -0.90093718
 -0.7145183  -0.45259276 -0.14330303  0.18130114  0.48659197  0.7403574
  0.91643661  0.9965421 ] [ 0.          0.32023024  0.60652416  0.82923013  0.96471037  0.99707609
  0.92487749  0.75561961  0.50622543  0.20309642 -0.12113512 -0.43286389
 -0.69866663 -0.89035058 -0.98858757 -0.9831743  -0.8726784  -0.67035805
 -0.3977518  -0.0830894 ]


## 97. Given an integer n and a 2D array X, select rows that can be interpreted as draws from a multinomial distribution with n degrees (i.e., rows for which np.sum(row) == n) (★★★)


In [103]:
n = 10
X = np.random.randint(0, 5, (10, 3))
rows = X[np.sum(X, axis=1) == n]
print(rows)



[[4 3 3]
 [4 2 4]]


## 98. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (★★★)


In [104]:
X = np.random.randn(100)
means = [np.mean(np.random.choice(X, size=X.shape[0], replace=True)) for _ in range(1000)]
conf_int = np.percentile(means, [2.5, 97.5])
print(conf_int)



[0.00261693 0.35842989]


## 99. How to create a record array from a regular array? (★★★)


In [105]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
r = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'U8, f8, i8')
print(r)



[('Hello', 2.5, 3) ('World', 3.6, 2)]


## 100. Consider a large vector Z, compute Z to the power of 3 using three different methods (★★★)


In [110]:
Z = np.random.rand(10000)


In [112]:
Z_cubed1 = Z ** 3


In [113]:
Z_cubed2 = np.power(Z, 3)


In [114]:
Z_cubed3 = Z * Z * Z
